name: pull-request.schema

on:
  pull_request:
    branches:
      - main
    paths:
      - "schema/**"
  workflow_dispatch:

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - uses: kamilkisiela/graphql-inspector@v3.4.0
        with:
          schema: "main:schema/schema.graphql"
          annotations: false
